In [1]:
import pandas as pd

In [2]:
# Langkah 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

1. Input Data Kotor

In [3]:
kolom = ["ID_Karyawan", "Nama", "Jenis_Kelamin", "Departemen",
         "Jabatan", "Kota", "Status", "Tanggal_Masuk"]

data = [
    [1,  "Andi Saputra",     "L", "IT",        "Programmer",        "Malang",    "Aktif", "12/01/2022"],
    [2,  " siti aminah ",    "P", "HRD",       "HR Staff",          "malang",    "aktif", "2022-02-15"],
    [3,  "BUDI SANTOSO",     "L", "Finance",   "Accounting Staff",  "MALANG",    "AKTIF", "15-03-2022"],
    [4,  "Dewi Lestari",     "P", "Marketing", "Marketing Staff",   "Surabaya",  "Aktif", "20/04/2022"],
    [5,  "  Eko Prasetyo",   "L", "IT ",       "Network Engineer",  "Surabaya ", "aktif", "2022/05/10"],
    [6,  "Fitri Handayani",  "P", "hrd",       "Recruitment Staff", "Malang",    "AKTIF", "11-06-2022"],
    [7,  "Gilang Ramadhan",  "L", "Finance",   "Finance Staff",     "Batu",      "Aktif", "2022-07-18"],
    [8,  "Hana Putri",       "P", "Marketing", "Content Creator",   "batu",      "aktif", "25/08/2022"],
    [9,  "Irfan Maulana",    "L", "IT",        "programmer",        "MALANG",    "Aktif", "2022-09-12"],
    [10, "Joko Susilo",      "L", "HRD",       "HR Staff",          "Surabaya",  "AKTIF", "10/10/2022"],
    [11, "Kartika Sari",     "P", "Finance",   "Accounting Staff",  "malang",    "Aktif", "2022-11-05"],
    [12, "Lukman Hakim",     "L", "Marketing", "Marketing Staff",   "Malang",    "aktif", "01-12-2022"],
    [13, "Maya Anggraini",   "P", "IT",        "Network Engineer",  "Surabaya",  "Aktif", "2023-01-09"],
    [14, "Nanda Pratama",    "L", "HRD",       "Recruitment Staff", "surabaya",  "AKTIF", "15/02/2023"],
    [15, "Oki Setiawan",     "L", "Finance",   "Finance Staff",     "Batu",      "Aktif", "2023/03/20"],
    [16, "Putri Ayu",        "P", "Marketing", "Content Creator",   "Malang",    "aktif", "22-04-2023"],
    [17, "Rizky Firmansyah", "L", "IT",        "Programmer",        "malang",    "Aktif", "2023-05-11"],
    [18, "Sarah Amelia",     "P", "HRD",       "HR Staff",          "MALANG",    "AKTIF", "18/06/2023"],
    [19, "Taufik Hidayat",   "L", "Finance",   "Accounting Staff",  "Surabaya",  "Aktif", "2023-07-24"],
    [20, "Umi Kalsum",       "P", "Marketing", "Marketing Staff",   "surabaya",  "aktif", "2023-08-14"],
    [21, "Vina Maharani",    "P", "IT",        "Network Engineer",  "Malang",    "Aktif", "2023-09-07"],
    [22, "Wahyu Nugroho",    "L", "HRD",       "Recruitment Staff", "Batu",      "AKTIF", "2023/10/19"],
    [23, "Yuni Kartika",     "P", "Finance",   "Finance Staff",     "batu",      "Aktif", "2023-11-13"],
    [24, "Zainal Abidin",    "L", "Marketing", "Content Creator",   "Malang ",   "aktif", "05/12/2023"],
    [25, "  Aulia Rahma",    "P", "IT",        "Programmer",        "MALANG",    "Aktif", "2024-01-16"],
    [26, "Bayu Kurniawan",   "L", "HRD",       "HR Staff",          "Surabaya",  "AKTIF", "2024/02/21"],
    [27, "Citra Dewi",       "P", "Finance",   "Accounting Staff",  "malang",    "Aktif", "2024-03-08"],
    [28, "Dimas Arya",       "L", "Marketing", "Marketing Staff",   "Batu",      "aktif", "17-04-2024"],
    [29, "Elisa Novita",     "P", "IT",        "Network Engineer",  "Malang",    "Aktif", "2024-05-27"],
    [30, "Fajar Ramadhan",   "L", "HRD",       "Recruitment Staff", "surabaya",  "AKTIF", "2024-06-12"],
]

df = pd.DataFrame(data, columns=kolom)
df.head(10)

,ID_Karyawan,Nama,Jenis_Kelamin,Departemen,Jabatan,Kota,Status,Tanggal_Masuk
0,1,Andi Saputra,L,IT,Programmer,Malang,Aktif,12/01/2022
1,2,siti aminah,P,HRD,HR Staff,malang,aktif,2022-02-15
2,3,BUDI SANTOSO,L,Finance,Accounting Staff,MALANG,AKTIF,15-03-2022
3,4,Dewi Lestari,P,Marketing,Marketing Staff,Surabaya,Aktif,20/04/2022
4,5,Eko Prasetyo,L,IT,Network Engineer,Surabaya,aktif,2022/05/10
5,6,Fitri Handayani,P,hrd,Recruitment Staff,Malang,AKTIF,11-06-2022
6,7,Gilang Ramadhan,L,Finance,Finance Staff,Batu,Aktif,2022-07-18
7,8,Hana Putri,P,Marketing,Content Creator,batu,aktif,25/08/2022
8,9,Irfan Maulana,L,IT,programmer,MALANG,Aktif,2022-09-12
9,10,Joko Susilo,L,HRD,HR Staff,Surabaya,AKTIF,10/10/2022

2. Identifikasi Masalah pada Data

In [4]:
print(df.info())
print("\nNilai unik Departemen :", df["Departemen"].unique())
print("Nilai unik Kota       :", df["Kota"].unique())
print("Nilai unik Status     :", df["Status"].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Karyawan    30 non-null     int64
 1   Nama           30 non-null     object
 2   Jenis_Kelamin  30 non-null     object
 3   Departemen     30 non-null     object
 4   Jabatan        30 non-null     object
 5   Kota           30 non-null     object
 6   Status         30 non-null     object
 7   Tanggal_Masuk  30 non-null     object
dtypes: int64(1), object(7)
memory usage: 2.0+ KB
None

Nilai unik Departemen : ['IT' 'HRD' 'Finance' 'Marketing' 'IT ' 'hrd']
Nilai unik Kota       : ['Malang' 'malang' 'MALANG' 'Surabaya' 'Surabaya ' 'Batu' 'batu'
 'surabaya' 'Malang ']
Nilai unik Status     : ['Aktif' 'aktif' 'AKTIF']

3. Membuat Fungsi Pembersih

In [5]:
SINGKATAN = {"IT", "HRD"}
FORMAT_TANGGAL = ["%Y-%m-%d", "%Y/%m/%d",
                  "%d-%m-%Y", "%d/%m/%Y"]


def bersihkan_teks(x):
    """Hapus spasi di awal/akhir dan spasi ganda di tengah."""
    return " ".join(str(x).split())


def rapikan_departemen(x):
    x = bersihkan_teks(x)
    return x.upper() if x.upper() in SINGKATAN else x.title()


def ubah_tanggal(x):
    """Semua format tanggal -> YYYY-MM-DD."""
    x = bersihkan_teks(x)
    for fmt in FORMAT_TANGGAL:
        try:
            return pd.to_datetime(x, format=fmt)
        except ValueError:
            continue
    return pd.NaT

4. Menghapus Spasi Berlebih

In [6]:
for k in kolom:
    df[k] = df[k].apply(bersihkan_teks)

df.head()

,ID_Karyawan,Nama,Jenis_Kelamin,Departemen,Jabatan,Kota,Status,Tanggal_Masuk
0,1,Andi Saputra,L,IT,Programmer,Malang,Aktif,12/01/2022
1,2,siti aminah,P,HRD,HR Staff,malang,aktif,2022-02-15
2,3,BUDI SANTOSO,L,Finance,Accounting Staff,MALANG,AKTIF,15-03-2022
3,4,Dewi Lestari,P,Marketing,Marketing Staff,Surabaya,Aktif,20/04/2022
4,5,Eko Prasetyo,L,IT,Network Engineer,Surabaya,aktif,2022/05/10

5. Menyeragamkan Huruf dan Tipe Data

In [7]:
df["ID_Karyawan"]   = df["ID_Karyawan"].astype(int)
df["Nama"]          = df["Nama"].str.title()
df["Jenis_Kelamin"] = df["Jenis_Kelamin"].str.upper()
df["Departemen"]    = df["Departemen"].apply(rapikan_departemen)
df["Jabatan"]       = (df["Jabatan"].str.title()
                       .str.replace(r"\bHr\b", "HR", regex=True))
df["Kota"]          = df["Kota"].str.title()
df["Status"]        = df["Status"].str.title()

df.head()

,ID_Karyawan,Nama,Jenis_Kelamin,Departemen,Jabatan,Kota,Status,Tanggal_Masuk
0,1,Andi Saputra,L,IT,Programmer,Malang,Aktif,12/01/2022
1,2,Siti Aminah,P,HRD,HR Staff,Malang,Aktif,2022-02-15
2,3,Budi Santoso,L,Finance,Accounting Staff,Malang,Aktif,15-03-2022
3,4,Dewi Lestari,P,Marketing,Marketing Staff,Surabaya,Aktif,20/04/2022
4,5,Eko Prasetyo,L,IT,Network Engineer,Surabaya,Aktif,2022/05/10

6. Menyeragamkan Format Tanggal

In [8]:
df["Tanggal_Masuk"] = df["Tanggal_Masuk"].apply(ubah_tanggal)

print("Tanggal gagal dikonversi:", df["Tanggal_Masuk"].isna().sum())
df["Tanggal_Masuk"] = df["Tanggal_Masuk"].dt.strftime("%Y-%m-%d")
df.head(10)

Tanggal gagal dikonversi: 0

,ID_Karyawan,Nama,Jenis_Kelamin,Departemen,Jabatan,Kota,Status,Tanggal_Masuk
0,1,Andi Saputra,L,IT,Programmer,Malang,Aktif,2022-01-12
1,2,Siti Aminah,P,HRD,HR Staff,Malang,Aktif,2022-02-15
2,3,Budi Santoso,L,Finance,Accounting Staff,Malang,Aktif,2022-03-15
3,4,Dewi Lestari,P,Marketing,Marketing Staff,Surabaya,Aktif,2022-04-20
4,5,Eko Prasetyo,L,IT,Network Engineer,Surabaya,Aktif,2022-05-10
5,6,Fitri Handayani,P,HRD,Recruitment Staff,Malang,Aktif,2022-06-11
6,7,Gilang Ramadhan,L,Finance,Finance Staff,Batu,Aktif,2022-07-18
7,8,Hana Putri,P,Marketing,Content Creator,Batu,Aktif,2022-08-25
8,9,Irfan Maulana,L,IT,Programmer,Malang,Aktif,2022-09-12
9,10,Joko Susilo,L,HRD,HR Staff,Surabaya,Aktif,2022-10-10

7. Menghapus Duplikat dan Mengurutkan Data

In [9]:
df = df.drop_duplicates(subset="ID_Karyawan").sort_values("ID_Karyawan")
df = df.reset_index(drop=True)
print("Jumlah baris:", len(df))

Jumlah baris: 30

8. Validasi Hasil Pembersihan

In [10]:
print("Jenis_Kelamin :", sorted(df["Jenis_Kelamin"].unique()))
print("Departemen    :", sorted(df["Departemen"].unique()))
print("Kota          :", sorted(df["Kota"].unique()))
print("Status        :", sorted(df["Status"].unique()))

Jenis_Kelamin : ['L', 'P']
Departemen    : ['Finance', 'HRD', 'IT', 'Marketing']
Kota          : ['Batu', 'Malang', 'Surabaya']
Status        : ['Aktif']

9. Download Data Bersih

In [23]:
from google.colab import files

df.to_csv("data_bersih.csv", index=False)
df.to_excel("data_bersih.xlsx", index=False)

files.download("data_bersih.csv")
files.download("data_bersih.xlsx")

['Programmer' 'HR Staff' 'Accounting Staff' 'Marketing Staff'
 'Network Engineer' 'Recruitment Staff' 'Finance Staff' 'Content Creator']